# Welcome to Jekyll!
#

# Site settings
title: Lormez Audio Studio
description: |
  Producción de Podcast
owner: Laura (@lormez16) # or company name
email: lormez16@protonmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lormez16.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/lormez16>
  github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/lormez16@protonmail.com
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/channel/UCvpN4r09FFi9O9JkwEwofgw?view_as=subscriber
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
